version: '3.8'

services:
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - cmatenet
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - cmatenet
    depends_on:
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  chemistry-service:
    build:
      context: ./chemistry-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - cmatenet
    depends_on:
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - cmatenet
    depends_on:
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  learning-progress-service:
    build:
      context: ./learning-progress-service
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    networks:
      - cmatenet
    depends_on:
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker

networks:
  cmatenet:
    driver: bridge