version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-chemistry
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chemistry_learning
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql
    networks:
      - cmatenet
    restart: always

volumes:
  mysql-data:
    driver: local

networks:
  cmatenet:
    driver: bridge
